# A.6 정렬

In [53]:
import numpy as np
import pandas as pd

In [2]:
arr = np.random.randn(6)

In [3]:
arr

array([ 0.90044263,  0.47185437,  0.8639365 , -0.8831706 , -1.96395659,
       -1.01931834])

In [4]:
arr=np.random.randn(3,5)

In [5]:
arr

array([[ 0.94150472, -1.69718225,  0.19645487, -0.55622178,  1.48804787],
       [ 0.68106605,  0.28057216,  1.53449293, -0.33955367,  0.24965886],
       [-0.47562091, -0.52708739,  1.38848951,  1.66274737, -0.59778297]])

In [6]:
arr[:, 0].sort()

In [7]:
arr

array([[-0.47562091, -1.69718225,  0.19645487, -0.55622178,  1.48804787],
       [ 0.68106605,  0.28057216,  1.53449293, -0.33955367,  0.24965886],
       [ 0.94150472, -0.52708739,  1.38848951,  1.66274737, -0.59778297]])

In [8]:
arr = np.random.randn(5)

In [9]:
arr

array([0.42877989, 0.72653961, 1.4710689 , 1.10247905, 0.34341851])

In [10]:
np.sort(arr)

array([0.34341851, 0.42877989, 0.72653961, 1.10247905, 1.4710689 ])

In [11]:
arr

array([0.42877989, 0.72653961, 1.4710689 , 1.10247905, 0.34341851])

In [12]:
arr=np.random.randn(3, 5)

In [13]:
arr

array([[ 0.16637529,  0.42563839, -0.78230291, -0.17943736, -0.78915751],
       [-0.81703008, -1.00638556,  0.41667419,  0.16733587, -0.47051016],
       [ 0.02973802,  1.11419949,  0.7182387 ,  0.60324368,  1.90568673]])

In [14]:
arr.sort(axis=1)

In [15]:
arr

array([[-0.78915751, -0.78230291, -0.17943736,  0.16637529,  0.42563839],
       [-1.00638556, -0.81703008, -0.47051016,  0.16733587,  0.41667419],
       [ 0.02973802,  0.60324368,  0.7182387 ,  1.11419949,  1.90568673]])

In [16]:
arr[:, ::-1]

array([[ 0.42563839,  0.16637529, -0.17943736, -0.78230291, -0.78915751],
       [ 0.41667419,  0.16733587, -0.47051016, -0.81703008, -1.00638556],
       [ 1.90568673,  1.11419949,  0.7182387 ,  0.60324368,  0.02973802]])

## A.6.1 간접 정렬 : argsort와 lexsort

In [17]:
values = np.array([5,0,1,3,2])

In [18]:
indexer = values.argsort()

In [19]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [20]:
values[indexer]

array([0, 1, 2, 3, 5])

In [21]:
arr=np.random.randn(3, 5)

In [22]:
arr[0] = values

In [23]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-0.91437542, -0.73811123,  0.31566056,  0.0285682 , -1.51924213],
       [-2.12018111,  0.1736755 , -1.52274722, -1.40401554,  0.56455348]])

In [24]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.73811123,  0.31566056, -1.51924213,  0.0285682 , -0.91437542],
       [ 0.1736755 , -1.52274722,  0.56455348, -1.40401554, -2.12018111]])

In [25]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])

In [26]:
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

In [27]:
sorter = np.lexsort((first_name, last_name))

In [28]:
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [29]:
zip(last_name[sorter], first_name[sorter])

## A.6.2 대안 정렬 알고리즘

In [30]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])

In [31]:
key = np.array([2,2,1,1,1])

In [32]:
indexer = key.argsort(kind='mergesort')

In [33]:
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [34]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

## A.6.3 배열 일부만 정렬하기

In [35]:
np.random.seed(12345)

In [36]:
arr=np.random.randn(20)

In [37]:
arr

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163,  0.22891288,  1.35291684,
        0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974])

In [38]:
np.partition(arr,3)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [39]:
indices = np.argpartition(arr,3)

In [40]:
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9], dtype=int64)

In [41]:
arr.take(indices)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

## A.6.4 numpy.searchsorted : 정렬된 배열에서 원소 찾기

In [42]:
arr=np.array([0,1,7,12,15])

In [43]:
arr.searchsorted(9)

3

In [44]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5], dtype=int64)

In [45]:
arr= np.array([0,0,0,1,1,1,1])

In [46]:
arr.searchsorted([0,1])

array([0, 3], dtype=int64)

In [47]:
arr.searchsorted([0,1], side='right')

array([3, 7], dtype=int64)

In [48]:
data = np.floor(np.random.uniform(0, 10000, size=50))

In [49]:
bins = np.array([0,100,1000,5000,10000])

In [50]:
data

array([9940., 6768., 7908., 1709.,  268., 8003., 9037.,  246., 4917.,
       5262., 5963.,  519., 8950., 7282., 8183., 5002., 8101.,  959.,
       2189., 2587., 4681., 4593., 7095., 1780., 5314., 1677., 7688.,
       9281., 6094., 1501., 4896., 3773., 8486., 9110., 3838., 3154.,
       5683., 1878., 1258., 6875., 7996., 5735., 9732., 6340., 8884.,
       4954., 3516., 7142., 5039., 2256.])

In [51]:
labels=bins.searchsorted(data)

In [52]:
labels

array([4, 4, 4, 3, 2, 4, 4, 2, 3, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 3, 3, 3,
       4, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 4, 4, 3], dtype=int64)

# B.3 소프트웨어 개발 도구

## B.3.1 대화형 디버거

In [58]:
run ipython_bug.py

AssertionError: 

In [59]:
run -d ipython_bug.py

Breakpoint 1 at c:\users\한지수\onedrive\바탕 화면\수da쟁이\ipython_bug.py:1
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> c:\users\한지수\onedrive\바탕 화면\수da쟁이\ipython_bug.py(1)<module>()
1---> 1 def works_fine():
      2     a = 5
      3     b = 6
      4     assert(a + b == 11)
      5 

ipdb> s
> c:\users\한지수\onedrive\바탕 화면\수da쟁이\ipython_bug.py(6)<module>()
      4     assert(a + b == 11)
      5 
----> 6 def throws_an_exception():
      7     a = 5
      8     b = 6

ipdb> b 12
Breakpoint 2 at c:\users\한지수\onedrive\바탕 화면\수da쟁이\ipython_bug.py:12
ipdb> c
> c:\users\한지수\onedrive\바탕 화면\수da쟁이\ipython_bug.py(12)calling_things()
     10 
     11 def calling_things():
2--> 12     works_fine()
     13     throws_an_exception()
     14 

ipdb> n
> c:\users\한지수\onedrive\바탕 화면\수da쟁이\ipython_bug.py(13)calling_things()
     11 def calling_things():
2    12     works_fine()
---> 13     throws_an_exception()
     14 
     15 calling_things()

ipdb> s
--Call--
> c:\users\한지수\onedrive\바탕 화면\수da쟁

## B.3.2 실행 시간 측정 : %time과 %timeit

In [61]:
import time

In [63]:
start = time.time()

In [64]:
strings = ['foo', 'foobar', 'baz', 'qux', 'python', 'Guido Van Rossum'] * 100000

In [67]:
method1 = [x for x in strings if x.startswith('foo')]

In [68]:
method2 = [x for x in strings if x[:3]=='foo']

In [70]:
%time method1 = [x for x in strings if x.startswith('foo')]

Wall time: 158 ms


In [71]:
%time method2 = [x for x in strings if x[:3]=='foo']

Wall time: 129 ms


In [73]:
%timeit [x for x in strings if x.startswith('foo')]

158 ms ± 5.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [74]:
%timeit [x for x in strings if x[:3]=='foo']

138 ms ± 5.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [75]:
x = 'foobar'
y = 'foo'

In [76]:
%timeit x.startswith(y)

337 ns ± 19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [77]:
%timeit x[:3] == y

317 ns ± 9.75 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## B.3.3 기본적인 프로파일링 : %prun과 %run -p

In [79]:
from numpy.random import randn

def add_and_sum(x,y) : 
    added=x+y
    summed = added.sum(axis=1)
    return summed

In [80]:
def call_function():
    x = randn(1000,1000)
    y = randn(1000,1000)
    return add_and_sum(x,y)

In [81]:
x=randn(3000,3000)
y=randn(3000,3000)

In [82]:
%prun add_and_sum(x,y)

In [83]:
!pip install line_profiler
%load_ext line_profiler

In [84]:
%lprun -f add_and_sum add_and_sum(x,y)

In [85]:
%lprun -f add_and_sum -f call_function call_function()