# A.1 ndarray 객체구조

In [1]:
import numpy as np

In [3]:
a=np.ones((10,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.ones((10,5)).shape
# shape 함수를 사용해 배열의 크기를 알아낼 수 있다.

(10, 5)

In [5]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [6]:
np.ones((3,4,5),dtype=np.float64).strides

(160, 40, 8)

## A.1 Numpy dtype 구조 

In [7]:
ints=np.ones(10,dtype=np.uint16)

In [8]:
floats=np.ones(10,dtype=np.float32)

In [9]:
np.issubdtype(ints.dtype,np.integer)

True

In [10]:
np.issubdtype(floats.dtype,np.floating)

True

In [11]:
np.float64.mro()
# 부모 클래스는 mro 메서드를 사용해서 알 수 있다.

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [12]:
np.issubdtype(ints.dtype,np.number)

True

# A.2 고급 배열 조작 기법

## A.2.1 배열 재형성하기

In [13]:
arr=np.arange(8)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
b=arr.reshape((4,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
c=arr.reshape((4,2),order='C')
c
# 'C' 로우 우선

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
d=arr.reshape((4,2),order='F')
d
# 'F' 컬럼 우선

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
other_arr=np.ones((3,5))
other_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
other_arr.shape

(3, 5)

In [24]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr=np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [26]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])